# create a image based on the latest verion of the official python image
# install the required packages
# zmq
# aiohttp
# requests

FROM base:latest

COPY master.py /app/master.py
# launch the bash prompt
CMD ["/bin/bash"]